version: 2

defaults: &defaults
  docker:
    - image: ubuntu:18.04
  steps:
    - checkout
    - run:
        name: setup prerequisites
        command: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y wget git build-essential file cpio unzip python bc rsync expect
    - run:
        name: Prepare build
        command: |
             git clone https://github.com/buildroot/buildroot.git && \
             cd buildroot && git checkout 650818fb3a
        no_output_timeout: 1200
    - run:
        name: Prepare config
        command: |
             cd buildroot/ && \
             cat configs/${target}_defconfig \
                     ../glibc_defconfig \
                     ../navit_defconfig \
                     > configs/navit_${target}_defconfig && \
             make BR2_EXTERNAL=../ defconfig && \
             make defconfig navit_${target}_defconfig
    - store_artifacts:
          path: buildroot/.config
          destination: buildroot-config
    - run:
        name: Build toolchain
        command: |
             cd buildroot/ && bash ../build.sh toolchain || (tail -n 200 br.log; exit 1)
        no_output_timeout: 1200
    - run:
        name: Build kernel
        command: |
             cd buildroot/ && bash ../build.sh linux-rebuild || (tail -n 200 br.log; exit 1)
        no_output_timeout: 1200
    - run:
        name: Build remaining packages
        command: |
             cd buildroot/ && bash ../build.sh || (tail -n 200 br.log; exit 1)
        no_output_timeout: 1200
    - store_artifacts:
          path: buildroot/output/images
          destination: output

jobs:
  raspberrypi2:
    <<: *defaults
    environment:
      target: raspberrypi2
  raspberrypi3:
    <<: *defaults
    environment:
      target: raspberrypi3

workflows:
  version: 2
  build_everything:
    jobs:
      - raspberrypi2
      - raspberrypi3
